package com.aotain.common.policyapi.mapper;

import com.aotain.common.config.annotation.MyBatisDao;
import com.aotain.common.policyapi.base.BaseMapper;
import com.aotain.common.policyapi.model.DpiV1CfgDpiinfo;

import java.util.List;

@MyBatisDao
public interface DpiV1CfgDpiinfoMapper extends BaseMapper{

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CU_V3.DPI_V1_CFG_DPIINFO
     *
     * @mbg.generated
     */
    int insertSelective(DpiV1CfgDpiinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CU_V3.DPI_V1_CFG_DPIINFO
     *
     * @mbg.generated
     */
    DpiV1CfgDpiinfo selectByPrimaryKey(Long devId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CU_V3.DPI_V1_CFG_DPIINFO
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DpiV1CfgDpiinfo record);

    /**
     * 根据dpiIp查询devId
     * @param dpiIp
     * @return
     */
    DpiV1CfgDpiinfo selectDevIdByDevIpAndOperationType(String dpiIp);

    /**
     * 查询所有的Eu通用设备信息
     * @return
     */
    List<DpiV1CfgDpiinfo> selectAllEuDeviceInfo();
    
    /**
     * 删除5000端口
     */
    void updatePortToEmpty();
}