package com.aotain.common.config.model;

import java.io.Serializable;

public class IdcJcdmJkcs implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CU_V3.IDC_JCDM_JKCS.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CU_V3.IDC_JCDM_JKCS.CS_KEY
     *
     * @mbg.generated
     */
    private String csKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CU_V3.IDC_JCDM_JKCS.CS_VALUE
     *
     * @mbg.generated
     */
    private String csValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CU_V3.IDC_JCDM_JKCS.CS_DESCRIBE
     *
     * @mbg.generated
     */
    private String csDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CU_V3.IDC_JCDM_JKCS.SRLX
     *
     * @mbg.generated
     */
    private Short srlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CU_V3.IDC_JCDM_JKCS.TYPE
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CU_V3.IDC_JCDM_JKCS.SFYX
     *
     * @mbg.generated
     */
    private Short sfyx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CU_V3.IDC_JCDM_JKCS.MODEL_TYPE
     *
     * @mbg.generated
     */
    private Short modelType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CU_V3.IDC_JCDM_JKCS.IS_PASSWORD
     *
     * @mbg.generated
     */
    private Short isPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CU_V3.IDC_JCDM_JKCS.ID
     *
     * @return the value of CU_V3.IDC_JCDM_JKCS.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CU_V3.IDC_JCDM_JKCS.ID
     *
     * @param id the value for CU_V3.IDC_JCDM_JKCS.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CU_V3.IDC_JCDM_JKCS.CS_KEY
     *
     * @return the value of CU_V3.IDC_JCDM_JKCS.CS_KEY
     *
     * @mbg.generated
     */
    public String getCsKey() {
        return csKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CU_V3.IDC_JCDM_JKCS.CS_KEY
     *
     * @param csKey the value for CU_V3.IDC_JCDM_JKCS.CS_KEY
     *
     * @mbg.generated
     */
    public void setCsKey(String csKey) {
        this.csKey = csKey == null ? null : csKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CU_V3.IDC_JCDM_JKCS.CS_VALUE
     *
     * @return the value of CU_V3.IDC_JCDM_JKCS.CS_VALUE
     *
     * @mbg.generated
     */
    public String getCsValue() {
        return csValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CU_V3.IDC_JCDM_JKCS.CS_VALUE
     *
     * @param csValue the value for CU_V3.IDC_JCDM_JKCS.CS_VALUE
     *
     * @mbg.generated
     */
    public void setCsValue(String csValue) {
        this.csValue = csValue == null ? null : csValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CU_V3.IDC_JCDM_JKCS.CS_DESCRIBE
     *
     * @return the value of CU_V3.IDC_JCDM_JKCS.CS_DESCRIBE
     *
     * @mbg.generated
     */
    public String getCsDescribe() {
        return csDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CU_V3.IDC_JCDM_JKCS.CS_DESCRIBE
     *
     * @param csDescribe the value for CU_V3.IDC_JCDM_JKCS.CS_DESCRIBE
     *
     * @mbg.generated
     */
    public void setCsDescribe(String csDescribe) {
        this.csDescribe = csDescribe == null ? null : csDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CU_V3.IDC_JCDM_JKCS.SRLX
     *
     * @return the value of CU_V3.IDC_JCDM_JKCS.SRLX
     *
     * @mbg.generated
     */
    public Short getSrlx() {
        return srlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CU_V3.IDC_JCDM_JKCS.SRLX
     *
     * @param srlx the value for CU_V3.IDC_JCDM_JKCS.SRLX
     *
     * @mbg.generated
     */
    public void setSrlx(Short srlx) {
        this.srlx = srlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CU_V3.IDC_JCDM_JKCS.TYPE
     *
     * @return the value of CU_V3.IDC_JCDM_JKCS.TYPE
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CU_V3.IDC_JCDM_JKCS.TYPE
     *
     * @param type the value for CU_V3.IDC_JCDM_JKCS.TYPE
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CU_V3.IDC_JCDM_JKCS.SFYX
     *
     * @return the value of CU_V3.IDC_JCDM_JKCS.SFYX
     *
     * @mbg.generated
     */
    public Short getSfyx() {
        return sfyx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CU_V3.IDC_JCDM_JKCS.SFYX
     *
     * @param sfyx the value for CU_V3.IDC_JCDM_JKCS.SFYX
     *
     * @mbg.generated
     */
    public void setSfyx(Short sfyx) {
        this.sfyx = sfyx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CU_V3.IDC_JCDM_JKCS.MODEL_TYPE
     *
     * @return the value of CU_V3.IDC_JCDM_JKCS.MODEL_TYPE
     *
     * @mbg.generated
     */
    public Short getModelType() {
        return modelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CU_V3.IDC_JCDM_JKCS.MODEL_TYPE
     *
     * @param modelType the value for CU_V3.IDC_JCDM_JKCS.MODEL_TYPE
     *
     * @mbg.generated
     */
    public void setModelType(Short modelType) {
        this.modelType = modelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CU_V3.IDC_JCDM_JKCS.IS_PASSWORD
     *
     * @return the value of CU_V3.IDC_JCDM_JKCS.IS_PASSWORD
     *
     * @mbg.generated
     */
    public Short getIsPassword() {
        return isPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CU_V3.IDC_JCDM_JKCS.IS_PASSWORD
     *
     * @param isPassword the value for CU_V3.IDC_JCDM_JKCS.IS_PASSWORD
     *
     * @mbg.generated
     */
    public void setIsPassword(Short isPassword) {
        this.isPassword = isPassword;
    }
}